# Generated by Django 6.0.2 on 2026-02-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_videogame_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='image',
        ),
    ]
