# Generated by Django 6.0.2 on 2026-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_videogame_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='image',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
